# Generated by Django 4.0.1 on 2022-03-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddNoteForm',
            new_name='Note',
        ),
    ]
