# Generated by Django 4.0.1 on 2022-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_reviews_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Review Contact',
                'verbose_name_plural': 'Reviews Contact',
            },
        ),
    ]
